package com.university.enrollment.util;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.io.ClassPathResource;
import org.springframework.stereotype.Component;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import com.university.enrollment.domain.Enrollment;
import com.university.enrollment.domain.EnrollmentId;
import com.university.enrollment.domain.Teaching;
import com.university.enrollment.domain.TeachingId;

@Component
@RequiredArgsConstructor
@Slf4j
public class DataMigrationRunner implements CommandLineRunner {

    private final com.university.enrollment.repository.StudentRepository studentRepository;
    private final com.university.enrollment.repository.CourseRepository courseRepository;
    private final com.university.enrollment.repository.ProfessorRepository professorRepository;
    private final com.university.enrollment.repository.EnrollmentRepository enrollmentRepository;
    private final com.university.enrollment.repository.TeachingRepository teachingRepository;

    @Override
    public void run(String... args) throws Exception {
        if (studentRepository.count() > 0) {
            log.info("Database already contains data. Skipping migration.");
            return;
        }

        log.info("Starting data migration from legacy files...");

        try {
            // Migrate Students (IDs auto-generated by DB)
            List<com.university.enrollment.domain.Student> students = loadStudents();
            students = studentRepository.saveAll(students);
            log.info("Migrated {} students", students.size());

            // Migrate Courses (IDs auto-generated by DB)
            List<com.university.enrollment.domain.Course> courses = loadCourses();
            courses = courseRepository.saveAll(courses);
            log.info("Migrated {} courses", courses.size());

            // Migrate Professors (IDs auto-generated by DB)
            List<com.university.enrollment.domain.Professor> professors = loadProfessors();
            professors = professorRepository.saveAll(professors);
            log.info("Migrated {} professors", professors.size());

            // Build lookup maps by actual DB-assigned IDs
            Map<Long, com.university.enrollment.domain.Student> studentMap = students.stream()
                    .collect(Collectors.toMap(com.university.enrollment.domain.Student::getId, Function.identity()));
            Map<Long, com.university.enrollment.domain.Course> courseMap = courses.stream()
                    .collect(Collectors.toMap(com.university.enrollment.domain.Course::getId, Function.identity()));
            Map<Long, com.university.enrollment.domain.Professor> professorMap = professors.stream()
                    .collect(Collectors.toMap(com.university.enrollment.domain.Professor::getId, Function.identity()));

            // Migrate Enrollments
            List<com.university.enrollment.domain.Enrollment> enrollments = loadEnrollments(studentMap, courseMap);
            enrollmentRepository.saveAll(enrollments);
            log.info("Migrated {} enrollments", enrollments.size());

            // Migrate Teaching assignments
            List<com.university.enrollment.domain.Teaching> teachings = loadTeachings(professorMap, courseMap);
            teachingRepository.saveAll(teachings);
            log.info("Migrated {} teaching assignments", teachings.size());

            log.info("Data migration completed successfully!");
        } catch (Exception e) {
            log.error("Error during data migration", e);
            throw e;
        }
    }

    private List<com.university.enrollment.domain.Student> loadStudents() throws Exception {
        ClassPathResource resource = new ClassPathResource("data-migration/students.txt");
        try (BufferedReader br = new BufferedReader(new InputStreamReader(resource.getInputStream()))) {
            return br.lines()
                    .filter(line -> !line.trim().isEmpty())
                    .map(line -> {
                        String[] parts = line.split(",");
                        // Do NOT set ID — let GenerationType.IDENTITY assign it
                        return com.university.enrollment.domain.Student.builder()
                                .firstName(parts[1].trim())
                                .lastName(parts[2].trim())
                                .age(Integer.parseInt(parts[3].trim()))
                                .semester(Integer.parseInt(parts[4].trim()))
                                .credits(Integer.parseInt(parts[5].trim()))
                                .build();
                    })
                    .toList();
        }
    }

    private List<com.university.enrollment.domain.Course> loadCourses() throws Exception {
        ClassPathResource resource = new ClassPathResource("data-migration/courses.txt");
        try (BufferedReader br = new BufferedReader(new InputStreamReader(resource.getInputStream()))) {
            return br.lines()
                    .filter(line -> !line.trim().isEmpty())
                    .map(line -> {
                        String[] parts = line.split(",");
                        return com.university.enrollment.domain.Course.builder()
                                .name(parts[1].trim())
                                .location(parts[2].trim())
                                .build();
                    })
                    .toList();
        }
    }

    private List<com.university.enrollment.domain.Professor> loadProfessors() throws Exception {
        ClassPathResource resource = new ClassPathResource("data-migration/professors.txt");
        try (BufferedReader br = new BufferedReader(new InputStreamReader(resource.getInputStream()))) {
            return br.lines()
                    .filter(line -> !line.trim().isEmpty())
                    .map(line -> {
                        String[] parts = line.split(",");
                        return com.university.enrollment.domain.Professor.builder()
                                .firstName(parts[1].trim())
                                .lastName(parts[2].trim())
                                .degree(parts[3].trim())
                                .employmentType(parts[4].trim())
                                .build();
                    })
                    .toList();
        }
    }

    private List<com.university.enrollment.domain.Enrollment> loadEnrollments(
            Map<Long, com.university.enrollment.domain.Student> studentMap,
            Map<Long, com.university.enrollment.domain.Course> courseMap) throws Exception {

        ClassPathResource resource = new ClassPathResource("data-migration/enrollments.txt");
        try (BufferedReader br = new BufferedReader(new InputStreamReader(resource.getInputStream()))) {
            return br.lines()
                    .filter(line -> !line.trim().isEmpty())
                    .map(line -> {
                        String[] parts = line.split(",");
                        Long studentId = Long.parseLong(parts[0].trim());
                        Long courseId = Long.parseLong(parts[1].trim());

                        com.university.enrollment.domain.Student student = studentMap.get(studentId);
                        com.university.enrollment.domain.Course course = courseMap.get(courseId);

                        if (student == null || course == null) {
                            log.warn("Skipping enrollment: studentId={}, courseId={} - not found in migrated data", studentId, courseId);
                            return null;
                        }

                        return com.university.enrollment.domain.Enrollment.builder()
                                .id(new EnrollmentId(studentId, courseId))
                                .student(student)
                                .course(course)
                                .price(new BigDecimal("100.00"))
                                .enrolledAt(LocalDateTime.now())
                                .build();
                    })
                    .filter(java.util.Objects::nonNull)
                    .toList();
        }
    }

    private List<com.university.enrollment.domain.Teaching> loadTeachings(
            Map<Long, com.university.enrollment.domain.Professor> professorMap,
            Map<Long, com.university.enrollment.domain.Course> courseMap) throws Exception {

        ClassPathResource resource = new ClassPathResource("data-migration/teaching.txt");
        try (BufferedReader br = new BufferedReader(new InputStreamReader(resource.getInputStream()))) {
            return br.lines()
                    .filter(line -> !line.trim().isEmpty())
                    .map(line -> {
                        String[] parts = line.split(",");
                        Long professorId = Long.parseLong(parts[0].trim());
                        Long courseId = Long.parseLong(parts[1].trim());

                        com.university.enrollment.domain.Professor professor = professorMap.get(professorId);
                        com.university.enrollment.domain.Course course = courseMap.get(courseId);

                        if (professor == null || course == null) {
                            log.warn("Skipping teaching assignment: professorId={}, courseId={} - not found in migrated data", professorId, courseId);
                            return null;
                        }

                        return com.university.enrollment.domain.Teaching.builder()
                                .id(new TeachingId(professorId, courseId))
                                .professor(professor)
                                .course(course)
                                .build();
                    })
                    .filter(java.util.Objects::nonNull)
                    .toList();
        }
    }
}
